### ISSUE TITLE
Extension missing in stack-volume-attach script

### ISSUE THREAD

**Issue by cojoj** [Jodel/aws-instance-scripts#1]
I know it's not necessary, but changing the name to simply `stack-volume-attach.sh` would be a nice way to indicate to the text editor of your choice which syntax highlighting to choose 😉

![](http://i.giphy.com/ebDRUtNexLV28.gif)

**Comment by discordianfish** [comment]
Your text editor should figure out the type without a need for an extension. Beside that, `.sh` suggests it might be a portable / non-bash shell script which it is not. In general most shell scripts on linux systems have no .sh extension, especially if they are in $PATH.

Not having an extension also conforms with the Google Bash style guide: https://google.github.io/styleguide/shell.xml?showone=File_Extensions#File_Extensions
